"""``chainbreak evidence export --archive`` (M18 F4, S1): a self-contained,
scrubbed tarball that a fresh machine can interpret with no repository
checkout -- the bundle, the resolved (compiled) scenario, the capability
catalog as it was at run time, the JSON Schemas, and a generated
``REPRODUCE.md`` naming the exact commands and versions.

``--archive`` always implies ``--public`` scrubbing (S1): this module builds
directly on top of :func:`chainbreak.evidence.export.export_public`'s
already-scrubbed staging output rather than reading the raw bundle itself,
so there is no code path that could archive an unscrubbed artifact.

Schema and catalog files are loaded with ``importlib.resources`` from the
installed distribution.  ``--archive`` therefore works from a wheel in an
empty directory and never silently consults a repository checkout.
"""

from __future__ import annotations

import tempfile
from dataclasses import dataclass
from importlib import resources
from pathlib import Path
from typing import Final

from chainbreak.capabilities.loader import catalog_bytes
from chainbreak.core.errors import EvidenceError
from chainbreak.evidence.export import ExportReport, export_public
from chainbreak.evidence.manifest import hash_bytes
from chainbreak.evidence.reader import read_manifest
from chainbreak.evidence.writer import create_tar_archive

__all__ = ["ArchiveReport", "create_archive"]

#: JSON Schema files only (the milestone's own words: "the JSON Schemas"),
#: not schemas/run-index.sql -- that describes the SQLite run-index cache
#: (DECISIONS.md: "a cache, never a source of truth"), not the bundle.
_SCHEMA_GLOB: Final = "*.schema.json"


def _packaged_schemas() -> tuple[tuple[str, bytes], ...]:
    root = resources.files("chainbreak._packaged_data").joinpath("schemas")
    if not root.is_dir():
        # Editable source checkouts do not contain the wheel's force-included
        # mirror. Installed distributions never take this branch.
        root_path = Path(__file__).resolve().parents[3] / "schemas"
        return tuple(
            (path.name, path.read_bytes()) for path in sorted(root_path.glob(_SCHEMA_GLOB))
        )
    return tuple(
        (item.name, item.read_bytes())
        for item in sorted(root.iterdir(), key=lambda item: item.name)
        if item.name.endswith(_SCHEMA_GLOB.removeprefix("*"))
    )


@dataclass(frozen=True, slots=True)
class ArchiveReport:
    run_id: str
    archive_path: Path
    export_report: ExportReport
    schema_files: tuple[str, ...]
    catalog_version: str


def _reproduce_md(
    *,
    run_id: str,
    manifest_provenance: dict[str, object],
    scenario_ref: dict[str, object],
) -> str:
    chainbreak_version = manifest_provenance.get("chainbreak_version", "unknown")
    provider = manifest_provenance.get("provider", "unknown")
    adapter_version = manifest_provenance.get("provider_adapter_version", "unknown")
    catalog_version = manifest_provenance.get("capability_catalog_version", "unknown")
    catalog_fingerprint = manifest_provenance.get("capability_catalog_fingerprint", "unknown")
    python_version = manifest_provenance.get("python_version", "unknown")
    seed = manifest_provenance.get("seed")
    scenario_id = scenario_ref.get("id", "unknown")
    compiled_hash = scenario_ref.get("compiled_hash", "unknown")

    seed_line = (
        f"--seed {seed}"
        if seed is not None
        else "--seed <not recorded in this bundle -- see manifest.json>"
    )
    seed_note = (
        ""
        if seed is not None
        else (
            "\n> This bundle predates provenance.seed (M18); the exact seed used for this "
            "run is not recoverable from it. compiled_hash and the rest of provenance below "
            "still let you verify you are running the same scenario against the same "
            "adapter/catalog versions.\n"
        )
    )

    return f"""# Reproducing run {run_id}

Generated by `chainbreak evidence export --archive`. See REPRODUCIBILITY.md
in the CHAINBREAK repository for what "reproducible" means at each of the
three levels this bundle supports.
{seed_note}
## Versions this run was produced with

| Field | Value |
|---|---|
| chainbreak_version | {chainbreak_version} |
| provider | {provider} |
| provider_adapter_version | {adapter_version} |
| capability_catalog_version | {catalog_version} |
| capability_catalog_fingerprint | {catalog_fingerprint} |
| python_version | {python_version} |
| scenario id | {scenario_id} |
| compiled_hash | {compiled_hash} |

## Commands

```bash
chainbreak run scenarios/<path-matching-{scenario_id}> --provider {provider} {seed_line}
chainbreak analyze <new-run-id>
chainbreak compare {run_id} <new-run-id>
```

`compare` refuses to compare across a differing `compiled_hash`,
`adapter_version` or `catalog_version` without `--allow-heterogeneous`
(REPRODUCIBILITY.md section 1) -- a refusal here means your environment is
not running the same thing this bundle recorded, which is itself useful
information.

## What is in this archive

- `bundle/` -- the scrubbed evidence bundle (manifest, observations, events,
  policy states, credentials, graph, resolved scenario, environment, and
  `findings.json`/`scores.json` if `chainbreak analyze` had already run).
- `catalog.yaml` -- the capability catalog as it was at run time
  (version {catalog_version}). A bundle without its schema and catalog is
  uninterpretable once either evolves.
- `schemas/` -- every JSON Schema the bundle's artifacts validate against.
"""


def create_archive(
    run_dir: Path,
    *,
    output_path: Path | None = None,
    include_policy_documents: bool = False,
) -> ArchiveReport:
    """Build a self-contained, scrubbed tarball at ``output_path`` (default:
    ``<run_dir.parent>/<run_id>-archive.tar.gz``).

    Refuses (raising :class:`~chainbreak.core.errors.EvidenceError`) rather
    than archiving a mismatch: a catalog whose version does not match what
    this run actually recorded would silently mislabel the archived
    environment, and an archive is exactly the artifact someone else relies
    on to trust that label.
    """
    manifest = read_manifest(run_dir / "manifest.json")

    from chainbreak.capabilities.loader import load_catalog

    catalog_data = catalog_bytes()
    recorded_catalog_version = str(manifest.provenance.get("capability_catalog_version", ""))
    current_catalog = load_catalog()
    if current_catalog.version != recorded_catalog_version:
        raise EvidenceError(
            f"catalog.yaml on disk is version {current_catalog.version}, but run "
            f"{manifest.run_id} recorded capability_catalog_version="
            f"{recorded_catalog_version!r}; archiving would silently mislabel the "
            "catalog this run actually used. Check out the matching version before "
            "archiving.",
            run_id=manifest.run_id,
            recorded_catalog_version=recorded_catalog_version,
            current_catalog_version=current_catalog.version,
        )

    recorded_catalog_fingerprint = manifest.provenance.get("capability_catalog_fingerprint")
    current_catalog_fingerprint = hash_bytes(catalog_data)
    if recorded_catalog_fingerprint is not None and str(recorded_catalog_fingerprint) != (
        current_catalog_fingerprint
    ):
        raise EvidenceError(
            f"catalog.yaml content has changed since run {manifest.run_id}: recorded "
            f"fingerprint={recorded_catalog_fingerprint!r}, current="
            f"{current_catalog_fingerprint!r}; archiving would not contain the catalog "
            "as it was at run time",
            run_id=manifest.run_id,
            recorded_catalog_fingerprint=str(recorded_catalog_fingerprint),
            current_catalog_fingerprint=current_catalog_fingerprint,
        )

    schema_data = _packaged_schemas()
    if not schema_data:
        raise EvidenceError("no packaged JSON Schemas are available", run_id=manifest.run_id)

    reproduce_md = _reproduce_md(
        run_id=manifest.run_id,
        manifest_provenance=dict(manifest.provenance),
        scenario_ref=dict(manifest.scenario),
    )

    # Scrub into a temporary staging directory rather than export_public's
    # own default (a permanent <run_id>-public sibling directory): --archive
    # promises exactly one artifact, the tarball. The staging tree is
    # removed once it has been read into the tar, regardless of outcome.
    with tempfile.TemporaryDirectory(prefix=f"chainbreak-archive-{manifest.run_id}-") as tmp:
        staging_dir = Path(tmp) / "bundle"
        export_report = export_public(
            run_dir,
            output_dir=staging_dir,
            dry_run=False,
            include_policy_documents=include_policy_documents,
        )

        members: dict[str, Path | bytes] = {
            f"{manifest.run_id}/bundle/{path.relative_to(staging_dir)}": path
            for path in sorted(staging_dir.rglob("*"))
            if path.is_file()
        }
        members[f"{manifest.run_id}/catalog.yaml"] = catalog_data
        for schema_name, schema_bytes in schema_data:
            members[f"{manifest.run_id}/schemas/{schema_name}"] = schema_bytes
        members[f"{manifest.run_id}/REPRODUCE.md"] = reproduce_md.encode("utf-8")

        archive_path = output_path or run_dir.parent / f"{manifest.run_id}-archive.tar.gz"
        create_tar_archive(archive_path, members)

    return ArchiveReport(
        run_id=manifest.run_id,
        archive_path=archive_path,
        export_report=export_report,
        schema_files=tuple(name for name, _ in schema_data),
        catalog_version=current_catalog.version,
    )
