#!/usr/bin/env python3
"""Generate chainbreak.toml and terraform.tfvars from a live AWS SSO session.

Run this once, after `aws sso login`. It reads the account id and the caller's
role from STS/IAM rather than asking you to copy them by hand -- a mistyped
account id in the allowlist is the one configuration error the safety model
cannot catch for you (SI-6 refuses a wrong account, but it cannot tell that the
*right-looking* account you typed is not the one you meant).

Writes two gitignored files:
    chainbreak.toml
    infra/terraform/environments/aws-sandbox/terraform.tfvars

Neither is overwritten without --force.

Usage:
    aws sso login --profile chainbreak
    python scripts/bootstrap_aws_config.py --profile chainbreak --region eu-central-1
"""

from __future__ import annotations

import argparse
import json
import re
import secrets
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = REPO_ROOT / "chainbreak.toml"
TFVARS_PATH = REPO_ROOT / "infra/terraform/environments/aws-sandbox/terraform.tfvars"

ACCOUNT_RE = re.compile(r"^\d{12}$")
ASSUMED_ROLE_RE = re.compile(r"^arn:aws[a-z-]*:sts::(\d{12}):assumed-role/([^/]+)/")


def aws(args: list[str], profile: str, region: str) -> dict:
    """Run an AWS CLI command and return parsed JSON."""
    cmd = ["aws", *args, "--profile", profile, "--region", region, "--output", "json"]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        stderr = proc.stderr.strip()
        if "sso" in stderr.lower() or "token" in stderr.lower() or "expired" in stderr.lower():
            fail(
                f"AWS call failed -- your SSO session looks expired or absent.\n"
                f"  Run:  aws sso login --profile {profile}\n\n"
                f"  {stderr}"
            )
        fail(f"AWS call failed: {' '.join(cmd)}\n  {stderr}")
    return json.loads(proc.stdout)


def fail(message: str) -> None:
    print(f"\n  ERROR  {message}\n", file=sys.stderr)
    raise SystemExit(1)


def resolve_operator_role_arn(assumed_role_arn: str, profile: str, region: str) -> str:
    """Turn an STS assumed-role ARN into the underlying IAM role ARN.

    SSO roles live under a path (``/aws-reserved/sso.amazonaws.com/<region>/``)
    that the STS ARN omits, and a trust policy needs the full path form. Ask IAM
    rather than reconstructing it -- the path contains the SSO instance region,
    which is not necessarily the region you are benchmarking in.
    """
    match = ASSUMED_ROLE_RE.match(assumed_role_arn)
    if not match:
        return ""
    role_name = match.group(2)
    try:
        role = aws(["iam", "get-role", "--role-name", role_name], profile, region)
    except SystemExit:
        return ""
    return str(role["Role"]["Arn"])


def render_config(account_id: str, region: str) -> str:
    return f"""# CHAINBREAK configuration -- generated by scripts/bootstrap_aws_config.py
#
# This file is gitignored. It names a real account, so it must never be
# committed. Regenerate it rather than editing by hand if the account changes.

[safety]
# SI-6: explicit 12-digit account ids only, no wildcards. A run against any
# other account is refused after exactly one AWS call (GetCallerIdentity).
allowed_account_ids = ["{account_id}"]
allowed_regions = ["{region}"]
namespace_prefix = "cb"

# SI-7 / SI-8 hard ceilings.
max_run_duration_seconds = 1800
max_estimated_cost_usd = 1.0
max_delegation_depth = 6

allow_dangerous_capabilities = false
allow_concurrent_runs = false
require_confirmation_for_apply = true

[provider]
name = "aws"
region = "{region}"

[aws]
profile = "chainbreak"
"""


def render_tfvars(account_id: str, region: str, operator_arn: str, salt: str, email: str) -> str:
    arn_line = (
        f'  "{operator_arn}",'
        if operator_arn
        else (
            "  # Could not resolve your SSO role ARN automatically. Add it here:\n"
            "  # aws iam list-roles --query \"Roles[?contains(RoleName,'AWSReservedSSO')].Arn\""
        )
    )
    return f"""# CHAINBREAK aws-sandbox -- generated by scripts/bootstrap_aws_config.py
#
# Gitignored. Names a real account; never commit.

expected_account_id = "{account_id}"
region              = "{region}"
namespace_salt      = "{salt}"

# Who may assume the bootstrap and principal roles.
operator_principal_arns = [
{arn_line}
]

budget_limit_usd          = 5
budget_notification_email = "{email}"

# Keep true for real experiment blocks: a negative control run against
# different infrastructure than the scenarios it validates proves less.
enable_negative_controls = true

# Off by default -- CloudTrail data events are billed per event, and its
# delivery latency is minutes, far coarser than the sub-second intervals the
# revocation family measures.
enable_cloudtrail  = false
enable_data_events = false

scratch_expiry_days = 1
log_retention_days  = 1
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--profile", default="chainbreak")
    parser.add_argument("--region", default="eu-central-1")
    parser.add_argument("--email", default="", help="Budgets alarm notification address")
    parser.add_argument("--salt", default="", help="Namespace salt (random if omitted)")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    args = parser.parse_args()

    print(f"\n  Reading identity from profile '{args.profile}' in {args.region} ...")
    identity = aws(["sts", "get-caller-identity"], args.profile, args.region)

    account_id = str(identity["Account"])
    caller_arn = str(identity["Arn"])
    if not ACCOUNT_RE.match(account_id):
        fail(f"STS returned an implausible account id: {account_id!r}")

    print(f"    account  {account_id}")
    print(f"    caller   {caller_arn}")

    operator_arn = resolve_operator_role_arn(caller_arn, args.profile, args.region)
    if operator_arn:
        print(f"    role     {operator_arn}")
    else:
        print("    role     could not resolve automatically -- see the note in terraform.tfvars")

    salt = args.salt or secrets.token_hex(8)

    targets = [
        (CONFIG_PATH, render_config(account_id, args.region)),
        (TFVARS_PATH, render_tfvars(account_id, args.region, operator_arn, salt, args.email)),
    ]

    existing = [p for p, _ in targets if p.exists()]
    if existing and not args.force:
        names = ", ".join(str(p.relative_to(REPO_ROOT)) for p in existing)
        fail(f"refusing to overwrite: {names}\n  Re-run with --force if that is what you want.")

    for path, content in targets:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"    wrote    {path.relative_to(REPO_ROOT)}")

    print(
        "\n  Next:\n"
        "    chainbreak validate\n"
        "    chainbreak infra plan aws-sandbox\n"
        "    chainbreak infra apply aws-sandbox\n"
    )

    if not args.email:
        print(
            "  Note: budget_notification_email is empty, so the $5 Budgets alarm will\n"
            "  fire silently. Set it in terraform.tfvars if you want to be told.\n"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
